<?php

namespace BBLDN\AdCOMLaravel\Enum;

enum AgentTypeEnum: int
{
    case AN_ID_WHICH_IS_TIED_TO_A_SPECIFIC_WEB_BROWSER_OR_DEVICE = 1;

    case IN_APP_IMPRESSIONS_WHICH_WILL_TYPICALLY_CONTAIN_A_TYPE_OF_DEVICE_ID = 2;

    case A_PERSON_BASED_ID_I_E__THAT_IS_THE_SAME_ACROSS_DEVICES = 3;
}
