<?php

namespace BBLDN\AdCOMLaravel\Enum;

enum PlaybackMethodEnum: int
{
    case INITIATES_ON_PAGE_LOAD_WITH_SOUND_ON = 1;

    case INITIATES_ON_PAGE_LOAD_WITH_SOUND_OFF_BY_DEFAULT = 2;

    case INITIATES_ON_CLICK_WITH_SOUND_ON = 3;

    case INITIATES_ON_MOUSE_OVER_WITH_SOUND_ON = 4;

    case INITIATES_ON_ENTERING_VIEWPORT_WITH_SOUND_ON = 5;

    case INITIATES_ON_ENTERING_VIEWPORT_WITH_SOUND_OFF_BY_DEFAULT = 6;

    case CONTINUOUS_PLAYBACK = 7;
}
